=== JoelRodrigues58/DAW/TP2-a79068/manifesto.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT manifesto (meta,equipa,resumo,resultados) >

<!ELEMENT meta (identificador,titulo,subtitulo?,dinicio?,dfim,supervisor) >
<!ELEMENT identificador (#PCDATA) >
<!ELEMENT titulo (#PCDATA) >
<!ELEMENT dfim (#PCDATA) >
<!ELEMENT dinicio (#PCDATA) >
<!ELEMENT subtitulo (#PCDATA) >


<!ELEMENT supervisor (nome,email) >
<!ELEMENT nome (#PCDATA) >
<!ATTLIST nome 
            url CDATA #IMPLIED>
<!ELEMENT email (#PCDATA) >
<!ELEMENT website (#PCDATA) >



<!ELEMENT equipa (membro)+ >
<!ELEMENT membro (identificador,nome,email,foto?) >
<!ELEMENT foto EMPTY >
<!ATTLIST foto 
        src CDATA #REQUIRED >


<!ELEMENT resumo (para)+ >
<!ELEMENT para (#PCDATA | b | i | ul | code | table)* >
<!ELEMENT b (#PCDATA)>
<!ELEMENT i (#PCDATA)>
<!ELEMENT code (#PCDATA)>
<!ELEMENT table (tr)+ >
<!ELEMENT tr (td | th)* >
<!ELEMENT td (#PCDATA | imagem)* >
<!ELEMENT th (#PCDATA | imagem)* >
<!ELEMENT imagem EMPTY >
<!ATTLIST imagem 
        src CDATA #REQUIRED >

<!ELEMENT ul (li)+ >
<!ELEMENT li (#PCDATA | b)* >

<!ELEMENT resultados (resultado)+ >
<!ELEMENT resultado  (#PCDATA)>
<!ATTLIST resultado 
            url CDATA #REQUIRED>

=== JoelRodrigues58/DAW/TP2-a79068/manifesto.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/JoelRodrigues/Documents/MIEI/4Ano/1Semestre/DA_Web/2-TPC/manifesto.dtd">

<manifesto>
    <meta>
        <identificador>MIEI_2018_Web</identificador>
        <titulo>DTDs,XML,HTML</titulo>
        <dinicio> 26 de setembro de 2018</dinicio>
        <dfim>30 de setembro de 2018</dfim>
        <supervisor>
            <nome url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</nome>
            <email>jcr@di.uminho.pt</email>
        </supervisor>
    </meta>
    <equipa>
        <membro>
            <identificador>a79068</identificador>
            <nome>Joel Soares Rodrigues</nome>
            <email>a79068@alunos.uminho.pt</email>
            <foto src="foto.JPG"/>
        </membro>
    </equipa>
    <resumo>
        <para>
            Em primeiro lugar, neste trabalho foi desenvolvido um <i>Document Type Defenition</i> com o objetivo de estruturar um ficheiro <b>XML</b> que contém a 
            informação relativa ao presente documento. Este ficheiro <b>XML</b> terá obrigatoriamente de obdecer a todas as regras estabelecidas para poder ser validado.
           
        </para>
        <para>
            Seguidamente, sendo que o objetivo era elaborar um ficheiro <b>HTML</b> que representa a página atual, foi necessária a concretização de um ficheiro <b>XSLT</b>
            que tem como objetivo a transformação do <b>XML</b> em <b>HTML</b>.
        </para>  
        <para>
            Finalmente, de modo a ir de encontro a um outro objetivo paralelo, foi desenvolvido novamente um <i>Document Type Defenition</i> mas agora para estruturar e validar 
            ficheiros da plataforma <i>clav.dglab.gov.pt</i>.
        </para>
       
    </resumo>
    <resultados>
        <resultado url="manifesto.dtd">Manifesto dtd </resultado>
        <resultado url="manifesto.xml">Manifesto xml </resultado>
        <resultado url="manifesto.xsl">Manifesto xsl</resultado>
        <resultado url="manifesto.html">Manifesto html</resultado>
        <resultado url="pn.dtd">Pn dtd</resultado>
    </resultados>
</manifesto>

=== JoelRodrigues58/DAW/TP3-a79068/manifesto-tp3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/JoelRodrigues/Documents/MIEI/4Ano/1Semestre/DA_Web/2-TPC/manifesto.dtd">

<manifesto>
    <meta>
        <identificador>MIEI_2018_Web</identificador>
        <titulo>WebSite - Quran</titulo>
        <dinicio> 3 de outubro de 2018</dinicio>
        <dfim>8 de outubro de 2018</dfim>
        <supervisor>
            <nome url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</nome>
            <email>jcr@di.uminho.pt</email>
        </supervisor>
    </meta>
    <equipa>
        <membro>
            <identificador> a79068</identificador>
            <nome> Joel Soares Rodrigues</nome>
            <email> a79068@alunos.uminho.pt</email>
            <foto src="foto.JPG"/>
        </membro>
    </equipa>
    <resumo>
        <para>
            O objetivo deste trabalho era elaborar um <i>website</i> que traduzisse a informação presente num ficheiro <b>XML</b> proposto pela equipa docente que 
            resultaria da escolha de entre o livro do Alcorão e o livro de Mormon, neste caso foi selecionado o livro Alcorão.
        </para>
        <para>
            Numa primeira fase procedeu-se a um estudo prévido da estrutura do ficheiro fornecido, nomeadamente os elementos e informação relevante para passar para o <i>website</i>.
        </para>  
        <para>
            Tendo isto, foi implementado um ficheiro <b>XSLT</b> com o objetivo de definir a apresentação do ficheiro <b>XML</b> no <i>browser</i>. 
            Destaca-se ainda o uso de índices para manter a informação organizada. Isto é, cada capítulo do livro é traduzido numa página <i>web</i> e indexado ao índice de capítulos. É possível ainda navegar no <i>website</i> de forma a percorrer todos os capítulos desejados. 
            
        </para>
       
    </resumo>
    <resultados>
        <resultado url="website/index.html">WebSite Quran Book</resultado>
        <resultado url="quran.xsl">Quran xsl </resultado>
        <resultado url="manifesto-tp3.html">Manifesto html </resultado>
        <resultado url="manifesto-tp3.xml">Manifesto xml </resultado>
        <resultado url="manifesto-tp3.xsl">Manifesto xsl</resultado>
        <resultado url="quran.xml">Quran xml</resultado>
    </resultados>
</manifesto>

=== JoelRodrigues58/DAW/TP5-a79068/Manifesto/manifesto-tp5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/JoelRodrigues/Documents/MIEI/4Ano/1Semestre/DA_Web/2-TPC/manifesto.dtd">

<manifesto>
    <meta>
        <identificador>MIEI_2018_Web</identificador>
        <titulo>WebSite - Obras Músicais</titulo>
        <dinicio> 16 de outubro de 2018</dinicio>
        <dfim>22 de outubro de 2018</dfim>
        <supervisor>
            <nome url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</nome>
            <email>jcr@di.uminho.pt</email>
        </supervisor>
    </meta>
    <equipa>
        <membro>
            <identificador> a79068</identificador>
            <nome> Joel Soares Rodrigues</nome>
            <email> a79068@alunos.uminho.pt</email>
            <foto src="foto.JPG"/>
        </membro>
    </equipa>
    <resumo>
        <para>
            O objetivo deste trabalho era elaborar um servidor capaz de estar a escuta numa porta e que respondesse a pedidos <i>GET</i>. A funcionalidade do servidor é
            mostrar ao cliente páginas <i>HTML</i> de informação de uma base de dados de Obras músicais de uma banda.
        </para>
        <para>
            A base de dados é fornecida em ficheiros formato <i>json </i> onde cada um contem informação de uma música, nomeadamente os instrumentos. No entanto, não 
            existe um ficheiro que contenha todas as músicas indexadas. Portanto a primeira tarefa a desenvolver foi um <i>script</i> na linguagem <i>gawk</i> em duas componentes:
                <ul>
                    <li>1-Um primeiro programa que percorre todos os ficheiros JSON da diretoria e coleciona para um ficheiro os campos id,titulo e tipo de música. </li>
                    <li>2-Um segundo programa que pega no resultado do anterior e origina um índice de dois níveis, onde o primeiro é o tipo de música e o segundo
                    os títulos das músicas (selecionáveis).</li>
                </ul>
          
           </para>  
        <para>
            Depois de produzido o ficheiro <i>index.html</i> seguiu-se a fase de implementação do servidor. Para responder ao cliente com as diferentes páginas, foi
            usado o modulo <b>url</b> para fazer uma <i>parsing</i> ao url e apresentar os ficheiros solicitados, ou seja, quando o utilizador seleciona uma música 
            é lido o ficheiro da música cujo título foi o selecionado. Foram desenvolvidos também ficheiros <i>.pug</i> para tratar do <i>design</i> do servidor. 
        </para>
       
    </resumo>
    <resultados>
        <resultado url="https://github.com/JoelRodrigues58/DAW.git">Link github </resultado>
        <resultado url="manifesto-tp5.html">Manifesto html </resultado>
        <resultado url="manifesto-tp5.xml">Manifesto xml </resultado>
    </resultados>
</manifesto>

=== JoelRodrigues58/DAW/TP4-a79068/manifesto-tp4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE manifesto SYSTEM "file:/Users/JoelRodrigues/Documents/MIEI/4Ano/1Semestre/DA_Web/2-TPC/manifesto.dtd">

<manifesto>
    <meta>
        <identificador>MIEI_2018_Web</identificador>
        <titulo>WebSite - Arqueossítios do NW Português</titulo>
        <dinicio> 9 de outubro de 2018</dinicio>
        <dfim>15 de outubro de 2018</dfim>
        <supervisor>
            <nome url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</nome>
            <email>jcr@di.uminho.pt</email>
        </supervisor>
    </meta>
    <equipa>
        <membro>
            <identificador> a79068</identificador>
            <nome> Joel Soares Rodrigues</nome>
            <email> a79068@alunos.uminho.pt</email>
            <foto src="foto.JPG"/>
        </membro>
    </equipa>
    <resumo>
        <para>
            O objetivo deste trabalho era elaborar um servidor capaz de estar a escuta numa porta e que respondesse a pedidos <i>GET</i>. A funcionalidade do servidor é
            mostrar ao cliente páginas <i>HTML</i> de informação de uma base de dados de arqueossítios do NW Português.
        </para>
        <para>
            A primeira página que se apresenta no arranque do servidor é o índice de dois níveis, um primeiro que é o concelho, correspondente ao campo <i>CONCEL</i> do ficheiro
            de dados <i>XML</i>, e um segudo que é a identificação que corresponde ao campo <i>IDENTI</i>. 
           </para>  
        <para>
            Para tal foi necessário utilizar o modulo <i>URL</i>, de forma a fazer um <i>parsing</i> do <i>url</i>, e o modulo <i>FS</i> para fazer leitura de ficheiros.
            Numa primeira instância foi necessário alterar o ficheiro <i>XSL</i>, modificando as hiperligações, para quando o utilizador selecionar uma opção do índice
            o <i>url</i> seja modificado e assim possibitar a leitura do ficheiro solicitado. Neste sentido, decidiu-se implementar as hiperligações dos ficheiros indexados
            da seguinte forma <i> href="http://localhost:4004/arqelem?id={generate-id()}" </i>. No momento de seleção de um elemento do índice é feito <i>parsing</i> ao  <i> pathname</i> 
            do <i>url</i> e caso seja igual a "/arqelem" então é feita a pesquisa do identificador através da primitiva <i>url.query</i> e apresentado o ficheiro correspondente.
            
            
            
        </para>
       
    </resumo>
    <resultados>
        <resultado url="https://github.com/JoelRodrigues58/DAW.git">Link github </resultado>
        <resultado url="manifesto-tp4.html">Manifesto html </resultado>
        <resultado url="manifesto-tp4.xml">Manifesto xml </resultado>
    </resultados>
</manifesto>
